// Copyright 2019 The UNICORE Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file
//
// Author: Gaulthier Gain <gaulthier.gain@uliege.be>

package buildtool

const (
	CARES             = "c-ares"
	COMPILERRT        = "compiler-rt"
	DEVFS             = "devfs"
	DPDK              = "dpdk"
	EIGEN             = "eigen"
	FP16              = "fp16"
	FXDIV             = "fxdiv"
	INTELINTRINSICS   = "intel-intrinsics"
	LIBAXTLS          = "libaxtls"
	LIBBLOCK          = "libblock"
	LIBCXX            = "libcxx"
	LIBCXXABI         = "libcxxabi"
	LIBGO             = "libgo"
	LIBJVM            = "libjvm"
	LIBPROC           = "libproc"
	LIBRUBY           = "libruby"
	LIBRUST           = "librust"
	LIBUKSCHEDPREEMPT = "libukschedpreempt"
	LIBUNWIND         = "libunwind"
	LIBUUID           = "libuuid"
	LIBUV             = "libuv"
	LIBV8             = "libv8"
	LWIP              = "lwip"
	MICROPYTHON       = "micropython"
	MUSL              = "musl"
	NEWLIB            = "newlib"
	NOBLIM            = "noblim"
	NOLIBC            = "nolibc"
	OPENSSL           = "openssl"
	PFS9              = "9pfs"
	POSIXLIBDL        = "posix-libdl"
	POSIXPROCESS      = "posix-process"
	POSIXUSER         = "posix-user"
	PTHREADEMBEDDED   = "pthread-embedded"
	PTHREADPOOL       = "pthreadpool"
	PYTHON            = "python"
	RAMFS             = "ramfs"
	SYSCALLSHIM       = "syscallshim"
	UKALLOC           = "ukalloc"
	UKALLOCBBUDDY     = "ukallocbbuddy"
	UKARGPARSE        = "ukargparse"
	UKBOOT            = "ukboot"
	UKBUS             = "ukbus"
	UKDEBUG           = "ukdebug"
	UKLOCK            = "uklock"
	UKMPI             = "ukmpi"
	UKNETDEV          = "uknetdev"
	UKPCI             = "ukpci"
	UKSCHED           = "uksched"
	UKSCHEDCOOP       = "ukschedcoop"
	UKSGLIST          = "uksglist"
	UKSYSINFO         = "uksysinfo"
	UKSWRAND          = "ukswrand"
	UKTIMECONV        = "uktimeconv"
	UKTIME            = "uktime"
	VFSCORE           = "vfscore"
	ZLIB              = "zlib"
)
