---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  DOCKERFILE: package/docker/Dockerfile.gcc
  CONTEXT: .
  # BUILD_ARG_UK_ARCH: x86_64
  # BUILD_ARG_GCC_VERSION: 9.2.0
  # BUILD_ARG_BINUTILS_VERSION: 2.31.1
  # BUILD_ARG_GLIB_VERSION: 2.11

inputs:
  - name: kraft
    path: .

outputs:
  - name: image

caches:
  - path: cache

run:
  path: build
