---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
  - name: kraft
    path: .

params:
  DOCKERFILE: package/docker/Dockerfile.kraft
  CONTEXT: .
  # BUILD_ARG_GCC_VERSION: ((kraft_gcc_version))
  # BUILD_ARG_UK_ARCH: ((kraft_uk_arch))
  # BUILD_ARG_GCC_PREFIX: ((kraft_gcc_prefix))
  # BUILD_ARG_YTT_VERSION: ((kraft_ytt_version))
  # BUILD_ARG_YQ_VERSION: ((kraft_yq_version))

outputs:
  - name: image

caches:
  - path: cache

run:
  path: build
