---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: unikraft/kraft
    tag: latest-dev

inputs:
  - name: kraft
    path: .

run:
  path: bash
  args:
    - -cex
    - ((target_cmd))
